version: '3'
services:
  cake-judge:
    build: .
    ports:
      - 80:80
    links:
      - "mongo:mongo"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
