version: '3'
services:
  cake-judge:
    build: .
    ports:
      - 80:80
      - 443:443
    links:
      - "mongo:mongo"
      - "redis:redis"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
  redis:
    image: redis
