CREATE DATABASE IF NOT EXISTS `cake-judge`;
USE `cake-judge`;
CREATE TABLE `appconfigs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `header` varchar(200) NOT NULL,
  `pageSize` int(11) NOT NULL,
  `manager_ip` varchar(255) NOT NULL,
  `rankingmode_HSIC` varchar(255) NOT NULL,
  `enableMailer` tinyint(1) NOT NULL,
  `CandidateManager` varchar(255) NOT NULL,
  `systemMode` varchar(50) NOT NULL,
  `systemModeContestid` int(11) NOT NULL,
  `consolePath` varchar(255) NOT NULL,
  `system_closed_message` varchar(255) NOT NULL,
  `problemid_prefix` varchar(10) NOT NULL,
  `problemtabs` text NOT NULL,
  `cryptKey` varchar(10) NOT NULL,
  `rsyncAccount` varchar(100) NOT NULL,
  `system_monitor_ip` varchar(255) NOT NULL,
  `competition_mode` varchar(255) NOT NULL,
  `rankingmode_NPSC` varchar(255) NOT NULL,
  `rankingmode_CSAPC` varchar(255) NOT NULL,
  `SystemMonitorAccount` varchar(255) NOT NULL,
  `titleImage` mediumblob NOT NULL,
  `logo` mediumblob NOT NULL,
  `threshold` double NOT NULL,
  `Locales` varchar(255) NOT NULL,
  `schemas` text NOT NULL,
  `exclusiveSchoolids` varchar(255) NOT NULL,
  `cachedUser` tinyint(1) NOT NULL,
  `cachedContest` tinyint(1) NOT NULL,
  `cachedProblem` tinyint(1) NOT NULL,
  `rejudgeable` tinyint(1) NOT NULL,
  `allowedIP` varchar(255) NOT NULL,
  `judgeQueueSize` int(11) NOT NULL,
  `maxConnectionByIP` int(11) NOT NULL,
  `maxCodeLength` int(11) NOT NULL,
  `maxTestdata` int(11) NOT NULL,
  `SearchEngines` text NOT NULL,
  `bannedIPSet` text NOT NULL,
  `managers` varchar(200) NOT NULL,
  `banners` text NOT NULL,
  `SystemMail` varchar(255) NOT NULL,
  `SystemMailPassword` varchar(255) NOT NULL,
  `last_solutionid_for_RecountProblemidset` int(11) NOT NULL DEFAULT '0',
  `httpscrt` mediumblob NOT NULL,
  `enableReCaptcha` tinyint(1) NOT NULL,
  `site_key` varchar(255) NOT NULL DEFAULT '',
  `secret_key` varchar(255) NOT NULL DEFAULT '',
  `enableGoogleLogin` tinyint(1) NOT NULL,
  `client_id` varchar(255) NOT NULL DEFAULT '',
  `client_secret` varchar(255) NOT NULL DEFAULT '',
  `redirect_uri` varchar(255) NOT NULL DEFAULT '',
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

-- 比賽與參加者?

CREATE TABLE `contests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `problemids` varchar(255) NOT NULL,
  `scores` varchar(255) NOT NULL,
  `removedsolutionids` text NOT NULL,
  `ownerid` int(11) NOT NULL DEFAULT '0',
  `vclassid` int(11) NOT NULL DEFAULT '0',
  `userrules` text NOT NULL,
  `starttime` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  `timelimit` bigint(20) DEFAULT '6000000',
  `pausepoints` text NOT NULL,
  `title` varchar(200) NOT NULL DEFAULT '',
  `subtitle` text NOT NULL,
  `taskid` int(11) DEFAULT '0',
  `conteststatus` varchar(20) NOT NULL DEFAULT 'Contest.NotStart',
  `addonprivilege` varchar(100) NOT NULL,
  `rankingmode` varchar(20) NOT NULL DEFAULT 'NPSC',
  `freezelimit` int(11) NOT NULL DEFAULT '0',
  `config` int(11) NOT NULL DEFAULT '0',
  `visible` varchar(20) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE `contestants` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contestid` int(11) DEFAULT '0',
  `userid` int(11) NOT NULL DEFAULT '0',
  `teamaccount` varchar(100) NOT NULL DEFAULT '',
  `teamname` varchar(200) NOT NULL,
  `password` varchar(100) NOT NULL,
  `email` varchar(200) NOT NULL,
  `school` varchar(100) NOT NULL,
  `ipset` varchar(50) NOT NULL,
  `language` varchar(20) NOT NULL,
  `ac` int(11) DEFAULT '0',
  `aclist` varchar(255) NOT NULL,
  `submits` int(11) NOT NULL DEFAULT '0',
  `penalty` int(11) NOT NULL DEFAULT '0',
  `score` int(11) NOT NULL DEFAULT '0',
  `status` varchar(20) NOT NULL DEFAULT 'registed',
  `finishtime` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

-- 論壇

CREATE TABLE `forum` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userid` int(11) NOT NULL DEFAULT '0',
  `account` varchar(100) NOT NULL DEFAULT '',
  `reply` int(11) DEFAULT '0', -- 下一篇?
  `problemid` varchar(10) DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `articletype` varchar(50) NOT NULL DEFAULT 'forum',
  `content` text,
  `ipfrom` varchar(150) NOT NULL,
  `timestamp` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  `clicknum` int(11) NOT NULL DEFAULT '0',
  `hidden` varchar(50) DEFAULT 'open',
  PRIMARY KEY (`id`),
  KEY `userid` (`userid`,`account`,`reply`,`problemid`,`hidden`)
) DEFAULT CHARSET=utf8;

-- PM

CREATE TABLE `imessages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sender` varchar(200) NOT NULL DEFAULT '',
  `receiver` varchar(200) NOT NULL DEFAULT '',
  `subject` varchar(200) NOT NULL DEFAULT '',
  `content` text,
  `senttime` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  `sender_status` varchar(10) NOT NULL DEFAULT 'open',
  `receiver_status` varchar(10) NOT NULL DEFAULT 'unread',
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE `loginlog` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `userid` varchar(12) NOT NULL DEFAULT '',
  `useraccount` varchar(20) NOT NULL DEFAULT '',
  `ipfrom` varchar(150) NOT NULL,
  `ipinfo` varchar(100) NOT NULL DEFAULT '',
  `message` varchar(100) NOT NULL DEFAULT 'Unknown',
  `logintime` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  `logouttime` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  `staymin` varchar(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE `logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `method` varchar(20) NOT NULL,
  `uri` varchar(100) NOT NULL DEFAULT '',
  `session_account` varchar(100) NOT NULL,
  `ipaddr` varchar(150) NOT NULL,
  `tabid` varchar(20) NOT NULL,
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `stacktrace` text NOT NULL,
  `timestamp` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  PRIMARY KEY (`id`),
  KEY `timestamp` (`timestamp`)
) DEFAULT CHARSET=utf8;

CREATE TABLE `problems` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `problemid` varchar(20) NOT NULL DEFAULT '',
  `title` varchar(200) NOT NULL DEFAULT '',
  `testfilelength` int(11) NOT NULL,
  `timelimits` varchar(1024) NOT NULL DEFAULT '',
  `memorylimit` int(11) NOT NULL DEFAULT '65536',
  `backgrounds` varchar(255) NOT NULL DEFAULT '',
  `locale` varchar(20) NOT NULL DEFAULT 'zh_TW',
  `content` text NOT NULL,
  `theinput` text NOT NULL,
  `theoutput` text NOT NULL,
  `sampleinput` text NOT NULL,
  `sampleoutput` text NOT NULL,
  `hint` text NOT NULL,
  `language` varchar(25) NOT NULL DEFAULT 'CPP',
  `samplecode` text NOT NULL,
  `prejudgement` varchar(25) NOT NULL DEFAULT '',
  `serveroutputs` mediumtext NOT NULL,
  `comment` text NOT NULL,
  `scores` text NOT NULL,
  `alteroutdata` text NOT NULL,
  `judgemode` varchar(500) NOT NULL DEFAULT '',
  `difficulty` int(11) NOT NULL DEFAULT '0',
  `acnum` int(11) NOT NULL DEFAULT '0',
  `submitnum` bigint(20) NOT NULL DEFAULT '0',
  `clicknum` bigint(20) NOT NULL DEFAULT '0',
  `acusers` int(11) NOT NULL DEFAULT '0',
  `submitusers` int(11) NOT NULL DEFAULT '0',
  `lastsolutionid` int(11) NOT NULL DEFAULT '0',
  `ownerid` int(11) NOT NULL DEFAULT '0',
  `reference` varchar(200) NOT NULL,
  `sortable` varchar(255) NOT NULL,
  `keywords` varchar(255) NOT NULL,
  `inserttime` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  `updatetime` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  `tabid` varchar(100) NOT NULL,
  `wa_visible` int(11) NOT NULL DEFAULT '1',
  `display` varchar(10) NOT NULL DEFAULT 'hide',
  `reserved_text1` text NOT NULL,
  `reserved_text2` text NOT NULL,
  `reserved_text3` text NOT NULL,
  `reserved_text4` text NOT NULL,
  `reserved_text5` text NOT NULL,
  `reserved_text6` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `problemid` (`problemid`),
  KEY `display_tabid_problemid` (`display`,`tabid`,`problemid`),
  KEY `problemid_display_tabid` (`problemid`,`display`,`tabid`),
) DEFAULT CHARSET=utf8;

CREATE TABLE `solutions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userid` int(11) NOT NULL DEFAULT '0',
  `vclassid` int(11) NOT NULL DEFAULT '0',
  `pid` int(11) NOT NULL,
  `language` varchar(10) NOT NULL DEFAULT 'C++',
  `timeusage` bigint(20) NOT NULL DEFAULT '0',
  `memoryusage` int(11) NOT NULL DEFAULT '0',
  `exefilesize` int(11) NOT NULL DEFAULT '-1',
  `code` text NOT NULL,
  `codelength` int(11) NOT NULL DEFAULT '0',
  `judgement` int(11) NOT NULL DEFAULT '0',
  `codelocker` int(11) NOT NULL DEFAULT '1',
  `contestid` int(11) NOT NULL DEFAULT '0',
  `score` int(11) NOT NULL DEFAULT '0',
  `details` text NOT NULL,
  `serveroutputs` text NOT NULL,
  `ipfrom` varchar(150) NOT NULL,
  `submittime` datetime DEFAULT '2006-06-08 00:00:00',
  `visible` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `userid` (`userid`),
  KEY `contestid` (`contestid`),
  KEY `visible` (`visible`),
  KEY `statusid` (`judgement`),
  KEY `codelength` (`codelength`),
  KEY `pid` (`pid`),
  KEY `language` (`language`),
  KEY `visible_solutionid` (`visible`,`id`),
  KEY `contestid_solutionid` (`contestid`,`id`),
  KEY `judgement_solutionid` (`judgement`,`id`),
  KEY `judgement_visible_solutionid` (`judgement`,`visible`,`id`),
  KEY `pid_judgement_visible_solutionid` (`pid`,`judgement`,`visible`,`id`),
  KEY `pid_userid_visible_solutionid` (`pid`,`userid`,`visible`,`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE `testcodes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` text NOT NULL,
  `language` varchar(50) NOT NULL,
  `indata` text NOT NULL,
  `outdata` text NOT NULL,
  `expected_status` varchar(50) NOT NULL,
  `actual_status` varchar(50) NOT NULL,
  `actual_detail` text NOT NULL,
  `descript` text NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;


CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `account` varchar(255) NOT NULL DEFAULT '',
  `authhost` varchar(255) DEFAULT 'localhost',
  `username` varchar(100) NOT NULL DEFAULT '',
  `md5passwd` varchar(50) NOT NULL DEFAULT '',
  `truename` varchar(20) NOT NULL DEFAULT '',
  `birthyear` int(5) NOT NULL DEFAULT '0',
  `schoolid` int(11) NOT NULL DEFAULT '0',
  `vclassid` int(11) NOT NULL DEFAULT '0',
  `email` varchar(50) NOT NULL DEFAULT '',
  `picture` text NOT NULL,
  `pictureblob` mediumblob NOT NULL,
  `picturetype` varchar(200) NOT NULL,
  `sessionid` varchar(50) NOT NULL DEFAULT '',
  `comment` varchar(255) NOT NULL DEFAULT '',
  `role` varchar(100) NOT NULL DEFAULT 'GUEST',
  `createby` int(11) NOT NULL,
  `label` varchar(200) NOT NULL DEFAULT '',
  `joinedcontestid` int(20) DEFAULT '0',
  `extraprivilege` varchar(255) NOT NULL DEFAULT '',
  `ipset` varchar(100) NOT NULL,
  `country` varchar(10) NOT NULL DEFAULT 'Unknown',
  `ipinfo` varchar(100) NOT NULL DEFAULT 'Unknown',
  `registertime` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  `lastlogin` datetime NOT NULL DEFAULT '2006-06-08 00:00:00',
  `lastsolutionid` int(11) NOT NULL DEFAULT '0',
  `userlanguage` varchar(10) NOT NULL DEFAULT 'CPP',
  `ac` int(11) NOT NULL DEFAULT '0',
  `aclist` text NOT NULL,
  `triedset` text NOT NULL,
  `wa` int(11) NOT NULL DEFAULT '0',
  `tle` int(11) NOT NULL DEFAULT '0',
  `mle` int(11) NOT NULL DEFAULT '0',
  `ole` int(11) NOT NULL DEFAULT '0',
  `re` int(11) NOT NULL DEFAULT '0',
  `ce` int(11) NOT NULL DEFAULT '0',
  `config` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `NONCLUSTERED` (`account`),
  KEY `account` (`schoolid`,`vclassid`,`joinedcontestid`,`config`,`account`)
) DEFAULT CHARSET=utf8;

CREATE TABLE `schools` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(255) NOT NULL,
  `schoolname` varchar(100) DEFAULT NULL,
  `imgsrc` varchar(255) NOT NULL,
  `descript` text NOT NULL,
  `checkid` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `url` (`url`),
  UNIQUE KEY `name` (`schoolname`)
) DEFAULT CHARSET=utf8;
