CREATE DATABASE IF NOT EXISTS `cake-judge`;
USE `cake-judge`;
CREATE TABLE `settings`(
  id INT PRIMARY KEY NOT NULL
  date DATE NOT NULL
);
CREATE TABLE `users`(
  id INT PRIMARY KEY NOT NULL
  name VARCHAR(255) NOT NULL
  email VARCHAR(255) NOT NULL
  password VARCHAR(255) NOT NULL
  salt VARCHAR(255) NOT NULL
);
CREATE TABLE `problems`(
  id INT PRIMARY KEY NOT NULL
);
CREATE TABLE `submits`(
  id INT PRIMARY KEY NOT NULL
);